# Generated by Django 2.2.1 on 2019-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_product_number_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='simo', max_length=250),
            preserve_default=False,
        ),
    ]
